name: Deployment Actions

on: deployment_status

jobs:
  dump_github_event:
    uses: ./.github/workflows/dump_event.yml

  # Example deployment status triggered job
  example:
    # Only want to run on success, otherwise it might be "pending", or "failure".
    if: ${{ (github.event.deployment_status.state == 'success') }}
    name: Example Job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      - name: Log out URL
        run: echo $BASE_URL
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
